import React from "react";
import Navbar from "./Navbar";
import data from "./Data";
import Card from "./dataCard";
import Footer from "./Footer";


function App() {
    const travelReport = data.map(function (item) {
        return <Card
            key={item.id}
            img={item.imgUrl}
            location={item.location}
            description={item.description}
            title={item.title}

        />
    })
    return (
        <>
            <Navbar />
            {/* I'm passing an inline styling because this is a new array thats generated by our map function */}
            <div style={{ marginLeft: "10%", marginTop: "3%" }}>{travelReport}</div>
            <br />
            <Footer />
        </>

    )
}

export default App

